
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 24 15:44:49 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 25;
  public static final int SQ_BRACKETS_O = 48;
  public static final int CONST = 7;
  public static final int EQ_TO = 32;
  public static final int LE_EQ = 37;
  public static final int REM = 30;
  public static final int SQ_BRACKETS_C = 49;
  public static final int SEMI = 43;
  public static final int CONTINUE = 17;
  public static final int NUM_CONST = 23;
  public static final int MINUS = 27;
  public static final int AND = 38;
  public static final int RECORD = 21;
  public static final int OR = 39;
  public static final int COMMA = 45;
  public static final int CLASS = 4;
  public static final int INC = 40;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 31;
  public static final int SUPER = 19;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int FULL_STOP = 42;
  public static final int BREAK = 3;
  public static final int IDENT = 22;
  public static final int VOID = 15;
  public static final int COL = 44;
  public static final int GT_EQ = 35;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int BRACKETS_O = 46;
  public static final int GOTO = 20;
  public static final int WHILE = 10;
  public static final int NOT_EQ_TO = 33;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 24;
  public static final int CUR_BRACKETS_O = 50;
  public static final int BRACKETS_C = 47;
  public static final int DEC = 41;
  public static final int GT = 34;
  public static final int PRINT = 12;
  public static final int DO = 9;
  public static final int CUR_BRACKETS_C = 51;
}

